//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1Fix.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckFacility
    {
        public int ID { get; set; }
        public string sn { get; set; }
        public string phonename { get; set; }
        public string color { get; set; }
        public string size { get; set; }
        public string @lock { get; set; }
        public string model { get; set; }
        public string jb { get; set; }
        public string country { get; set; }
        public Nullable<int> Contractmachine { get; set; }
        public Nullable<int> quality { get; set; }
        public Nullable<int> frametop { get; set; }
        public Nullable<int> framebottom { get; set; }
        public Nullable<int> frameleft { get; set; }
        public Nullable<int> frameright { get; set; }
        public Nullable<int> rearcover { get; set; }
        public Nullable<int> glass { get; set; }
        public Nullable<int> bottomscrew { get; set; }
        public Nullable<int> wifi { get; set; }
        public Nullable<int> bluetooth { get; set; }
        public Nullable<int> receiver { get; set; }
        public Nullable<int> microphone { get; set; }
        public Nullable<int> gyroscope { get; set; }
        public Nullable<int> camera { get; set; }
        public Nullable<int> signal { get; set; }
        public Nullable<int> headsethole { get; set; }
        public Nullable<int> chargehole { get; set; }
        public Nullable<int> fingerprint { get; set; }
        public Nullable<int> flash { get; set; }
        public Nullable<int> shooting { get; set; }
        public Nullable<int> battery { get; set; }
        public Nullable<int> powerbutton { get; set; }
        public Nullable<int> volumeup { get; set; }
        public Nullable<int> volumedown { get; set; }
        public Nullable<int> homebutton { get; set; }
        public Nullable<int> cardslot { get; set; }
        public Nullable<int> mutebutton { get; set; }
        public Nullable<int> brightness { get; set; }
        public Nullable<int> whiteblackreddisplay { get; set; }
        public Nullable<int> sensitivity { get; set; }
        public Nullable<int> wet { get; set; }
        public Nullable<int> insidelabel { get; set; }
        public Nullable<int> shield { get; set; }
        public Nullable<int> Partslocation { get; set; }
        public Nullable<int> screwtooth { get; set; }
        public string checkman { get; set; }
        public string checkid { get; set; }
        public string checkcity { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> PowerCable { get; set; }
        public Nullable<int> FrameButtonCable { get; set; }
        public Nullable<int> ChargeCable { get; set; }
        public Nullable<int> HomeButtonCable { get; set; }
        public Nullable<int> disks { get; set; }
        public Nullable<int> CPU { get; set; }
        public Nullable<int> vibration { get; set; }
        public Nullable<int> speaker { get; set; }
        public string nettype { get; set; }
        public Nullable<System.DateTime> Warranty { get; set; }
        public Nullable<System.DateTime> outboundTime { get; set; }
    }
}
