//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1Fix.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jm_Phone
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string PhoneID { get; set; }
        public string Color { get; set; }
        public string Ram { get; set; }
        public string CheckLevel { get; set; }
        public string sellMan { get; set; }
        public string Money1 { get; set; }
        public string Money2 { get; set; }
        public string Money3 { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> status { get; set; }
        public string OpenID { get; set; }
    }
}
