//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1Fix.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MicroMessage_Money
    {
        public int ID { get; set; }
        public string PhoneName { get; set; }
        public Nullable<int> EX { get; set; }
        public Nullable<int> VG { get; set; }
        public Nullable<int> GD { get; set; }
        public Nullable<int> FR { get; set; }
        public Nullable<int> OrderID { get; set; }
    }
}
