//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1Fix.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecyclePrice
    {
        public int ID { get; set; }
        public string Brand { get; set; }
        public string Product { get; set; }
        public Nullable<int> GoldenA1 { get; set; }
        public Nullable<int> GoldenA2 { get; set; }
        public Nullable<int> GoldenB1 { get; set; }
        public Nullable<int> GoldenB2 { get; set; }
        public Nullable<int> GoldenC1 { get; set; }
        public Nullable<int> GoldenC2 { get; set; }
        public Nullable<int> GoldenD1 { get; set; }
        public Nullable<int> GoldenD2 { get; set; }
        public Nullable<int> WhiteA1 { get; set; }
        public Nullable<int> WhiteA2 { get; set; }
        public Nullable<int> WhiteB1 { get; set; }
        public Nullable<int> WhiteB2 { get; set; }
        public Nullable<int> WhiteC1 { get; set; }
        public Nullable<int> WhiteC2 { get; set; }
        public Nullable<int> WhiteD1 { get; set; }
        public Nullable<int> WhiteD2 { get; set; }
        public Nullable<int> BlackA1 { get; set; }
        public Nullable<int> BlackA2 { get; set; }
        public Nullable<int> BlackB1 { get; set; }
        public Nullable<int> BlackB2 { get; set; }
        public Nullable<int> BlackC1 { get; set; }
        public Nullable<int> BlackC2 { get; set; }
        public Nullable<int> BlackD1 { get; set; }
        public Nullable<int> BlackD2 { get; set; }
        public string Text { get; set; }
    }
}
