//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1Fix.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SellDataEntities : DbContext
    {
        public SellDataEntities()
            : base("name=SellDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckImages> CheckImages { get; set; }
        public virtual DbSet<Jm_Phone> Jm_Phone { get; set; }
        public virtual DbSet<OrderList> OrderList { get; set; }
        public virtual DbSet<RecyclePrice> RecyclePrice { get; set; }
        public virtual DbSet<sellBrand> sellBrand { get; set; }
        public virtual DbSet<sellCate> sellCate { get; set; }
        public virtual DbSet<sellColorList> sellColorList { get; set; }
        public virtual DbSet<SellDate> SellDate { get; set; }
        public virtual DbSet<sellMemoryList> sellMemoryList { get; set; }
        public virtual DbSet<sellPrice> sellPrice { get; set; }
        public virtual DbSet<sellProduct> sellProduct { get; set; }
        public virtual DbSet<sellWayList> sellWayList { get; set; }
        public virtual DbSet<SellGenerateOrderNo> SellGenerateOrderNo { get; set; }
        public virtual DbSet<CheckFacility> CheckFacility { get; set; }
        public virtual DbSet<SellPhone> SellPhone { get; set; }
        public virtual DbSet<SellPhoneOrderDetail> SellPhoneOrderDetail { get; set; }
        public virtual DbSet<SellPhoneModel> SellPhoneModel { get; set; }
        public virtual DbSet<SellAddress> SellAddress { get; set; }
        public virtual DbSet<MicroMessage_Money> MicroMessage_Money { get; set; }
        public virtual DbSet<SellBaseImage> SellBaseImage { get; set; }
        public virtual DbSet<MicroMessage_NewPhone_Money> MicroMessage_NewPhone_Money { get; set; }
        public virtual DbSet<SuperUser> SuperUser { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<SellBaseInfo> SellBaseInfo { get; set; }
        public virtual DbSet<UserAddress> UserAddress { get; set; }
        public virtual DbSet<WxPayInfo> WxPayInfo { get; set; }
        public virtual DbSet<WxLog> WxLog { get; set; }
        public virtual DbSet<SellPhoneOrder> SellPhoneOrder { get; set; }
    
        public virtual ObjectResult<string> proc_GenerateOrderNo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_GenerateOrderNo");
        }
    }
}
