//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1Fix.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sellProduct
    {
        public int ID { get; set; }
        public Nullable<int> cate_id { get; set; }
        public int brand_id { get; set; }
        public string brand_name { get; set; }
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string Product_Color { get; set; }
        public string Product_WayList { get; set; }
        public string Product_MemoryList { get; set; }
    }
}
