//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1Fix.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellPhone
    {
        public int ID { get; set; }
        public Nullable<int> SellBaseInfoID { get; set; }
        public string Sn { get; set; }
        public Nullable<decimal> PersonPrice { get; set; }
        public Nullable<decimal> EnterprisePrice { get; set; }
        public Nullable<decimal> BigCustomerPrice { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> SellCategory { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> AddPerson { get; set; }
        public Nullable<int> ClickNum { get; set; }
        public string Title { get; set; }
    }
}
