//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1Fix.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellPhoneOrder
    {
        public int ID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OpenID { get; set; }
        public Nullable<int> UserInfoID { get; set; }
        public Nullable<int> UserAddressID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IsValid { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string OrderName { get; set; }
        public string BuyerEmail { get; set; }
        public string BuyerID { get; set; }
        public string TradeNo { get; set; }
        public Nullable<decimal> Totalfee { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string SendPerson { get; set; }
        public string SendCourierNo { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string CouponsNo { get; set; }
        public string CouponsUserID { get; set; }
        public string CouponsUserName { get; set; }
        public Nullable<decimal> CouponsPrice { get; set; }
    }
}
