//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1Fix.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellAddress
    {
        public int ID { get; set; }
        public string SellAddress1 { get; set; }
        public string Receiver { get; set; }
        public string ReceiverPhone { get; set; }
        public Nullable<int> IsDefault { get; set; }
    }
}
