//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1Fix.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sellPrice
    {
        public int sell_id { get; set; }
        public Nullable<int> brand_id { get; set; }
        public string brand_name { get; set; }
        public Nullable<int> product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> memory_id { get; set; }
        public string memory_name { get; set; }
        public Nullable<int> color_id { get; set; }
        public string color_name { get; set; }
        public Nullable<int> way_id { get; set; }
        public string way_name { get; set; }
        public Nullable<int> op_price_broken { get; set; }
        public Nullable<int> op_price_glass { get; set; }
        public Nullable<int> op_price_new { get; set; }
        public Nullable<int> op_price_normal { get; set; }
        public Nullable<int> sell_price_broken { get; set; }
        public Nullable<int> sell_price_glass { get; set; }
        public Nullable<int> sell_price_new { get; set; }
        public Nullable<int> sell_price_normal { get; set; }
    }
}
