//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1Fix.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellGenerateOrderNo
    {
        public int ID { get; set; }
        public string Prefix { get; set; }
        public string CurrDate { get; set; }
        public Nullable<int> Num { get; set; }
        public string CurrOrderNo { get; set; }
    }
}
