//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1Fix.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperUser
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string NickName { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public Nullable<bool> active { get; set; }
        public string TopLevel { get; set; }
    }
}
