//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1Fix.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public int ID { get; set; }
        public string user_name { get; set; }
        public string user_phone { get; set; }
        public string touch_time { get; set; }
        public string user_mail { get; set; }
        public string user_address { get; set; }
        public Nullable<int> is_default { get; set; }
        public string openid { get; set; }
        public Nullable<int> UserInfoID { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string area { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
